package com.casino.blackjack.model;

/**
 * Events broadcast by GameManager to all registered observers (Observer pattern).
 */
public enum GameEvent {
    STATE_CHANGED, CARD_DEALT, CARD_FLIPPED, BET_PLACED, BET_CLEARED,
    HAND_RESULT, ROUND_STARTED, ROUND_ENDED, INSURANCE_OFFERED, INSURANCE_RESOLVED,
    BLACKJACK_DETECTED, PLAYER_BUST, DEALER_BUST, BALANCE_CHANGED,
    ACHIEVEMENT_UNLOCKED, DAILY_REWARD_AVAILABLE, DAILY_REWARD_CLAIMED,
    SETTINGS_CHANGED, SHOE_RESHUFFLED, HINT_UPDATED, SPLIT_PERFORMED,
    DOUBLE_DOWN_PERFORMED, SURRENDER_PERFORMED, TIMER_TICK, TIMER_EXPIRED,
    SAVE_SUCCESS, LOAD_SUCCESS, ERROR
}
